name: CI

on: [push]

jobs:
  unit:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install MySQL 8
      run: sudo bash ./.github/scripts/mysql8.sh
    - name: Create Database
      run: mysql --user="homestead" --password="secret" -e "CREATE DATABASE testing character set UTF8mb4 collate utf8mb4_bin;"
    - name: Chromium Versison
      run: chromium-browser --version
